### ISSUE TITLE
搜索图书失败的解决办法

### ISSUE THREAD

**Issue by liuhongran626** [zhanghuanhao/LibrarySystem#12]
搜索图书失败是因为乱码问题，通过调试会发现从浏览器接受的书名字符串其实是乱码的，然后在web.xml里加上这么一段乱码过滤器就可以了。
 
    
    <filter>
        <filter-name>encodingFilter</filter-name>
        <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
        <init-param>
            <param-name>encoding</param-name>
            <param-value>utf-8</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>encodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

**Comment by zhanghuanhao** [comment]
可以创建一个pull request，我合进去
