### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by LonelyTangzz** [zhanghuanhao/LibrarySystem#14]
老哥，这里建议得闲完善下基础功能，类似于这种查询系统，至少需要分页吧。

**Comment by zhanghuanhao** [comment]
这个项目仅供初学者学习使用，分页功能暂不考虑加入到本系统。分页功能可以参考我的另一个项目 [NebulaMOOC](https://github.com/zhanghuanhao/NebulaMOOC)
