### ISSUE TITLE
提两个建议

### ISSUE THREAD

**Issue by Singularity0909** [zhanghuanhao/LibrarySystem#15]
1、请说明一下如果登录时连接数据库失败，可能是因为 JDBC 和本地 MySQL 版本冲突，可以在 pom.xml 第 18 行 `<mysql.version>5.1.29</mysql.version>` 修改成本地的 MySQL 版本。

2、数据库表设计可以把 admin 和 reader_card 合并，增加一个字段 is_admin 。

**Comment by WaveZhou** [comment]
> 1、请说明一下如果登录时连接数据库失败，可能是因为 JDBC 和本地 MySQL 版本冲突，可以在 pom.xml 第 18 行 `<mysql.version>5.1.29</mysql.version>` 修改成本地的 MySQL 版本。
> 
> 2、数据库表设计可以把 admin 和 reader_card 合并，增加一个字段 is_admin 。

为什么我跑不起来这个项目

**Comment by AmaduesBob** [comment]
为啥我是404

**Comment by AmaduesBob** [comment]
登录的按键无响应 有些功能还没有实现

**Comment by zhanghuanhao** [comment]
@AmaduesBob @WaveZhou 本地使用maven是可以跑起来，如果跑不起来先查看报错信息，很大可能是数据库连接异常或者没有初始化数据库

**Comment by zhanghuanhao** [comment]
@Singularity0909 这个建议不错。你可以fork之后进行修改，这只是个简单图书馆供初学者学习使用。

**Comment by frodot** [comment]
使用了MySQL8之后，需要修改的部分为pom,xml里面的java connect段的改成
      <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.12</version>
        </dependency>
然后在修改db.properties中的连接信息，
#mysql jdbc
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/library?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
jdbc.username=root
jdbc.password=123456
然后在点击mvn jetty run，进入localhost:8080就能正常登录
