### ISSUE TITLE
有两个小问题

### ISSUE THREAD

**Issue by CJJ-123456** [zhanghuanhao/LibrarySystem#17]
读者页面功能报错500   空指针异常
登陆界面按钮无响应

**Comment by Chien-W** [comment]
> 读者页面功能报错500空指针异常
> 登陆界面按钮无响应

登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！

**Comment by AmaduesBob** [comment]
> > 读者页面功能报错500空指针异常
> > 登陆界面按钮无响应
> 
> 登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！

请问为何我jetty跑还是无法登录

**Comment by Chien-W** [comment]
> > > 读者页面功能报错500空指针异常
> > > 登陆界面按钮无响应
> > 
> > 
> > 登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！
> 
> 请问为何我jetty跑还是无法登录

那就不清楚了，不过我现在的问题是，挂上服务器，报500

**Comment by AmaduesBob** [comment]
> > > > 读者页面功能报错500空指针异常
> > > > 登陆界面按钮无响应
> > > 
> > > 
> > > 登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！
> > 
> > 
> > 请问为何我jetty跑还是无法登录
> 
> 那就不清楚了，不过我现在的问题是，挂上服务器，报500

我登录起了无500，用maven下的jetty：run跑，跑完了直接到localhost：8080就可以登陆了，我之前是mysql的依赖出现了问题无法访问数据库

**Comment by Chien-W** [comment]
> > > > > 读者页面功能报错500空指针异常
> > > > > 登陆界面按钮无响应
> > > > 
> > > > 
> > > > 登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！
> > > 
> > > 
> > > 请问为何我jetty跑还是无法登录
> > 
> > 
> > 那就不清楚了，不过我现在的问题是，挂上服务器，报500
> 
> 我登录起了无500，用maven下的jetty：run跑，跑完了直接到localhost：8080就可以登陆了，我之前是mysql的依赖出现了问题无法访问数据库

我本地可以跑，但是我挂上服务器点登录就显示500

**Comment by JaysonAlbert** [comment]
> > 读者页面功能报错500空指针异常
> > 登陆界面按钮无响应
> 
> 登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！

我提了个pr，解决了这个问题

**Comment by Chien-W** [comment]
> > > 读者页面功能报错500空指针异常
> > > 登陆界面按钮无响应
> > 
> > 
> > 登录界面按钮无响应，我也发现了，用jetty跑，登录界面没问题，用tomcat跑，登陆界面的按钮就没反应了！
> 
> 我提了个pr，解决了这个问题

我好像发现了问题，是因为它的前端代码路径都没有写全，并且本地使用jetty跑的。所以最简单的方法，我是挂在了tomcat的root里面跑的，就没问题了。

**Comment by GaussYuan191** [comment]
我Tomcat运行不了

**Comment by GaussYuan191** [comment]
xhr.send( options.hasContent && options.data || null );  一直报这个错误

**Comment by zhanghuanhao** [comment]
我没有试过Tomcat运行，对于登录界面点击登录后没有反应的问题，大家可以仔细检查一下数据库连接是否正常，会不会连接不上。比如说，在db.properties文件里的配置是否正确，可能出现你设置的地址被防火墙拦住导致server连接不上mysql，服务器处于假死状态
