### ISSUE TITLE
登录页面ajax404

### ISSUE THREAD

**Issue by Scofieldicc** [zhanghuanhao/LibrarySystem#2]
requestMapping是那个路径，404

**Comment by zhanghuanhao** [comment]
https://github.com/zhanghuanhao/LibrarySystem/blob/eb8ec792977a9fa55b2d30f2ba330a8234a4f4a6/src/main/java/com/library/controller/LoginController.java#L134

**Comment by zhanghuanhao** [comment]
https://github.com/zhanghuanhao/LibrarySystem/blob/eb8ec792977a9fa55b2d30f2ba330a8234a4f4a6/src/main/java/com/library/controller/LoginController.java#L134-135

**Comment by zhanghuanhao** [comment]
https://github.com/zhanghuanhao/LibrarySystem/blob/eb8ec792977a9fa55b2d30f2ba330a8234a4f4a6/src/main/java/com/library/controller/LoginController.java#L132-L136

**Comment by Scofieldicc** [comment]
不是这个的问题，好像是我配置有问题，在别人电脑上用Firefox跑一次，我再跑就通了，很奇怪，但是问题解决了，谢谢你
