### ISSUE TITLE
项目启动报错了

### ISSUE THREAD

**Issue by xuefeng717** [zhanghuanhao/LibrarySystem#6]
![image](https://user-images.githubusercontent.com/52995577/67353649-99b8ee80-f585-11e9-8b7c-c8a098586dc4.png)

**Comment by zhanghuanhao** [comment]
![image](https://user-images.githubusercontent.com/32955627/67833793-a3f86100-fb20-11e9-8582-6dacd2de7ca0.png)
你的端口被占用了
