### ISSUE TITLE
thank's you share this project,i  login the system,but it aways don't response

### ISSUE THREAD

**Issue by 1149002591** [zhanghuanhao/LibrarySystem#9]

**Comment by zhanghuanhao** [comment]
Could you speak more clearly?

**Comment by 1149002591** [comment]
大佬，请问负责处理loginCheck的html页面在哪呀?ajax我还没学




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Walton"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 晚上6:01
收件人: "zhanghuanhao/LibrarySystem"<LibrarySystem@noreply.github.com&gt;; 
抄送: "葵夏"<1149002591@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhanghuanhao/LibrarySystem] thank&#39;s you share this project,i  login the system,but it aways don&#39;t response (#9)




Could you speak more clearly?

**Comment by zhanghuanhao** [comment]
https://github.com/zhanghuanhao/LibrarySystem/blob/c253367abcdda2c69b0d8f1e0c5a00437356b25f/src/main/webapp/WEB-INF/jsp/index.jsp#L100-L141
